#!/bin/bash
set -eu

app=olxparser
final_path=/opt/$app

systemctl stop $app || true
systemctl disable $app || true
rm -f /etc/systemd/system/$app.service
systemctl daemon-reload

rm -rf "$final_path"

ynh_remove_nginx_config
