#!/bin/bash
set -eu

app=olxparser
final_path=/opt/$app

systemctl stop $app

# Copy updated code
cp -r ../src/* "$final_path"

# Update dependencies
pip3 install -r "$final_path/requirements.txt"

systemctl restart $app
